#!/bin/bash

main() {

    prepare_file_permissions
    wait_for_db
    run_migrations
    optimize_app
    run_server "$@"

}

prepare_file_permissions() {
    chmod a+x ./artisan
}


wait_for_db() {
    echo "Waiting for DB to be ready"
    until ./artisan migrate:status 2>&1 | grep -q -E "(Migration table not found|Migration name)"; do
        sleep 1
    done
}

run_migrations() {
    ./artisan migrate
}

optimize_app() {
    ./artisan optimize:clear
    ./artisan optimize
}

run_server() {
    exec /usr/local/bin/docker-php-entrypoint "$@"
}

main "$@"
